language: rust


# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/wasm-pack


branches:
  only:
    - master
    - dev

matrix:

  include:


    - os    : linux
      rust  : stable
      script: cargo check

    - os  : linux
      rust: nightly
      dist: bionic

      addons:
        firefox: latest
        apt:
          packages:
            - libssl-dev # for cargo-tarpaulin
            - libgtk-3-dev # needed for headless (sic) firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1372998
            - libdbus-glib-1-dev # firefox

      # for wasm tests
      #
      install:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh


      script:
        - cargo test
        - cargo test --release
        - cargo doc --no-deps

        - wasm-pack test  --firefox --headless
        # - wasm-pack test  --chrome  --headless       #currently broken on travis try again later.

        - wasm-pack test  --firefox --headless --release
        # - wasm-pack test  --chrome  --headless --release       #currently broken on travis try again later.

        # code coverage
        #
        - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        - cargo tarpaulin --out Xml
        - bash <(curl -s https://codecov.io/bash)


    - os    : osx
      script:
        - cargo test
        - cargo test --release


    - os    : windows
      script:
        - cargo test
        - cargo test --release


