language: rust
rust    : nightly
cache   : cargo

matrix:

  include:

    - os: linux

      script:
        - ./ci-script.sh
        - rustup target add wasm32-unknown-unknown
        - rustup target add aarch64-linux-android
        - rustup target add x86_64-unknown-netbsd
        - cargo test --target wasm32-unknown-unknown
        - cargo test --target aarch64-linux-android
        - cargo test --target x86_64-unknown-netbsd

    - os    : osx
      script:
        - ./ci-script.sh
        - rustup target add aarch64-apple-ios
        - cargo test --target aarch64-apple-ios


    - os    : windows
      script: ./ci-script.sh

