language: rust
rust    : nightly
cache   : cargo

matrix:

  include:

    - os: linux

      script:
        - ./ci-script.sh
        - cargo test --target wasm32-unknown-unknown

    - os    : osx
      script: ./ci-script.sh


    - os    : windows
      script: ./ci-script.sh

